// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfIhyyWNAiGdFayArJEDqaNYERmRrWLnU',
    appId: '1:801646145871:web:6b22a67c2716e13bf4d53a',
    messagingSenderId: '801646145871',
    projectId: 'authenticationapp-4d348',
    authDomain: 'authenticationapp-4d348.firebaseapp.com',
    storageBucket: 'authenticationapp-4d348.firebasestorage.app',
    measurementId: 'G-5VCT15DCFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9kAJ_tZN3pw2CEC11sBYRnrmr00lBkFM',
    appId: '1:801646145871:android:7b946005a0330cfdf4d53a',
    messagingSenderId: '801646145871',
    projectId: 'authenticationapp-4d348',
    storageBucket: 'authenticationapp-4d348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBktlMa2E4gey5rtFKkrTJa5jwheqk6X1Q',
    appId: '1:801646145871:ios:b06a3cbd6cef6694f4d53a',
    messagingSenderId: '801646145871',
    projectId: 'authenticationapp-4d348',
    storageBucket: 'authenticationapp-4d348.firebasestorage.app',
    androidClientId: '801646145871-ng98mdfci8cjkjjjp2i1cubf843idstg.apps.googleusercontent.com',
    iosClientId: '801646145871-kfjchc9l04vdgdjfq5qm9mrd64u53chg.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBktlMa2E4gey5rtFKkrTJa5jwheqk6X1Q',
    appId: '1:801646145871:ios:b06a3cbd6cef6694f4d53a',
    messagingSenderId: '801646145871',
    projectId: 'authenticationapp-4d348',
    storageBucket: 'authenticationapp-4d348.firebasestorage.app',
    androidClientId: '801646145871-ng98mdfci8cjkjjjp2i1cubf843idstg.apps.googleusercontent.com',
    iosClientId: '801646145871-kfjchc9l04vdgdjfq5qm9mrd64u53chg.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfIhyyWNAiGdFayArJEDqaNYERmRrWLnU',
    appId: '1:801646145871:web:5c5c5e39a7b14e55f4d53a',
    messagingSenderId: '801646145871',
    projectId: 'authenticationapp-4d348',
    authDomain: 'authenticationapp-4d348.firebaseapp.com',
    storageBucket: 'authenticationapp-4d348.firebasestorage.app',
    measurementId: 'G-WGHB94KGYD',
  );
}
